# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  node_lts: # declares a reusable executor
    docker:
      - image: cimg/node:18.14.1

jobs:
  build:
    executor: node_lts
    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - yarn-v2-{{ checksum "yarn.lock" }}

      - run:
          name: install dependencies
          command: pnpm install --frozen-lockfile

      # - save_cache:
      #     key: yarn-v2-{{ checksum "yarn.lock" }}
      #     paths:
      #       - node_modules

      # # Run linting
      # - run: yarn lint

      # # Run type checking
      # - run: yarn lint:types

      # # Run tests
      # - run: yarn test:ci --reporter=junit --outputFile "./test-results.xml"

      # - store_test_results:
      #     path: ./test-results.xml

      # Build
      - run: yarn build

      # # Pass to other jobs
      # - persist_to_workspace:
      #     root: ./
      #     paths:
      #       - ./

workflows:
  complete:
    jobs:
      - build
